// <auto-generated />
using System;
using BwcAgent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BwcAgent.Migrations
{
    [DbContext(typeof(AgentDbContext))]
    partial class AgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BwcAgent.Models.Agent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateFrom");

                    b.Property<DateTime>("DateTo");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Remark");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("BwcAgent.Models.SaleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AgentId");

                    b.Property<decimal>("BaseCommission")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("IncreaseIfTargetMet")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Maximum")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Name");

                    b.Property<decimal>("RestToBase")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Target")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("TargetPeriod")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("SaleType");
                });

            modelBuilder.Entity("BwcAgent.Models.SaleType", b =>
                {
                    b.HasOne("BwcAgent.Models.Agent")
                        .WithMany("SaleTypes")
                        .HasForeignKey("AgentId");
                });
#pragma warning restore 612, 618
        }
    }
}
